name: Cucumber Java Junit Platform

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Start Selenium Docker Grid Setup
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Build with Maven
        run: mvn clean test
